// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjOVfqFeZR2h1JzgntqAYw6DtDXLXCwXQ',
    appId: '1:1023780741210:web:61cd5e369037aa1f323863',
    messagingSenderId: '1023780741210',
    projectId: 'social-app-9f667',
    authDomain: 'social-app-9f667.firebaseapp.com',
    storageBucket: 'social-app-9f667.appspot.com',
    measurementId: 'G-XLWPG121X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPEeysklyQRNn0eASWGx448HH50sdsS28',
    appId: '1:1023780741210:android:b4f8862fcc85fb64323863',
    messagingSenderId: '1023780741210',
    projectId: 'social-app-9f667',
    storageBucket: 'social-app-9f667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLt_Dk7XT6lXaP1tiCAMX7c-fYJXEBxNI',
    appId: '1:1023780741210:ios:8caaca7826185659323863',
    messagingSenderId: '1023780741210',
    projectId: 'social-app-9f667',
    storageBucket: 'social-app-9f667.appspot.com',
    iosClientId: '1023780741210-9iaqhsa0r7v4mqfobe9vkmpcbhclng6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLt_Dk7XT6lXaP1tiCAMX7c-fYJXEBxNI',
    appId: '1:1023780741210:ios:0a6bed800ed56067323863',
    messagingSenderId: '1023780741210',
    projectId: 'social-app-9f667',
    storageBucket: 'social-app-9f667.appspot.com',
    iosClientId: '1023780741210-tgu7d2ntq5vme8kt91m0agc72u8q2i2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
